export const NEWS_AMENITIES = [
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Өсөлт тэлэлт',
    label_en: 'Growth & Expansion',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Шинэ бүтээгдэхүүн',
    label_en: 'New Products',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Хамтын ажиллагаа',
    label_en: 'Cooperation',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Хөрөнгө оруулалт',
    label_en: 'Investment',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Амжилтын түүх',
    label_en: 'Success Stories',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Кампанит ажил',
    label_en: 'Campaigns',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Брэндинг',
    label_en: 'Branding',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Цахим шилжилт',
    label_en: 'Digital Transformation',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Инноваци',
    label_en: 'Innovation',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Байгууллагын соёл',
    label_en: 'Company Culture',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Нийгмийн хариуцлага',
    label_en: 'Corporate Social Responsibility',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Хууль эрх зүй',
    label_en: 'Legal',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Эдийн засаг',
    label_en: 'Economy',
    type: 'boolean',
  },
  {
    category_code: 'BTK',
    category: 'BTK Categories',
    label_mn: 'Судалгаа',
    label_en: 'Research',
    type: 'boolean',
  },
];
