export const PROJECT_AMENITIES = [
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Брайл тэмдэглэгээ',
    label_en: 'Braille signage',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Брайл/ярианы удирдлага лифтэнд',
    label_en: 'Braille/voice in elevator',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Пассаж, коридорын налуу',
    label_en: 'Corridor ramping',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Сонсголын туслах систем',
    label_en: 'Hearing loop / assistive listening',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Сул хараатай тэмдэглэгээ (high-contrast)',
    label_en: 'High-contrast signage',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Тактиль хавтан',
    label_en: 'Tactile paving',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Тусгай ариун цэврийн өрөө',
    label_en: 'Accessible restroom',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Тэргэнцэрийн налуу зам',
    label_en: 'Wheelchair ramp',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Тэргэнцэрийн өргөгч',
    label_en: 'Platform lift',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Шатгүй орох хэсэг',
    label_en: 'Step-free entrance',
    type: 'boolean',
  },
  {
    category_code: 'ACC',
    category: 'Accessibility & Inclusive Design',
    label_mn: 'Өргөн хаалга (≥90см)',
    label_en: 'Wide doors (≥90cm)',
    type: 'boolean',
  },

  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Low-E 2 давхар шил',
    label_en: 'Low-E double glazing',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Агуулах өрөө',
    label_en: 'Storage room',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Ачааны лифт',
    label_en: 'Freight elevator',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Бариулгүй орох хэсэг',
    label_en: 'Hands-free entry (auto door)',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Боох/чиплэх өрөө (хоол хүнс)',
    label_en: 'Food delivery staging room',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Дотор холбооны өрөө',
    label_en: 'Telecom/IDF rooms',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Дээврийн ашиглалттай талбай',
    label_en: 'Usable rooftop',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Консьерж ширээ',
    label_en: 'Concierge desk',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Курьерийн өрөө',
    label_en: 'Courier/package room',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Лифт',
    label_en: 'Elevator',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Тагт/лоджиа',
    label_en: 'Balcony/loggia',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Террас',
    label_en: 'Terrace',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Төхөөрөмжийн өрөө (BOH)',
    label_en: 'Back-of-house equipment rooms',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Хог буулгах шугам',
    label_en: 'Garbage chute',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Хүлэмжийн талбай',
    label_en: 'Greenhouse / winter garden',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Хүлээлгийн талбай',
    label_en: 'Waiting area',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Хүлээн авах лобби',
    label_en: 'Reception lobby',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mн: 'Хөгжим/дуу систем (PA)',
    label_en: 'Public address system',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Хөгжимгүй бүс (noise policy)',
    label_en: 'Quiet policy zones',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Шатны даралтжуулалт',
    label_en: 'Staircase pressurization',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Шилэн фасад',
    label_en: 'Curtain wall / glazed facade',
    type: 'boolean',
  },
  {
    category_code: 'BLD',
    category: 'Building Features',
    label_mn: 'Шуудангийн хайрцаг',
    label_en: 'Mailboxes',
    type: 'boolean',
  },

  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mn: 'Party room',
    label_en: 'Party room',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mn: 'АТМ/Банк салбар',
    label_en: 'ATM / bank branch',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mn: 'Амьтны арчилгаа',
    label_en: 'Pet grooming',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Дотор усан бассейн',
    label_en: 'Indoor swimming pool',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Зочдын унтлагын өрөө',
    label_en: 'Guest suite',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mn: 'Илгээмжийн шкаф/locker',
    label_en: 'Delivery lockers',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mn: 'Йог/аэробик студи',
    label_en: 'Yoga / aerobic studio',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mn: 'Кино өрөө',
    label_en: 'Cinema / screening room',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mn: 'Коворкинг талбай',
    label_en: 'Coworking space',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Кофе шоп/бэйкери',
    label_en: 'Cafe / bakery',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Музык/бүжгийн студи',
    label_en: 'Music / dance studio',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Номын/уншлагын өрөө',
    label_en: 'Library / reading room',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Орон суугчдын клуб/ивент танхим',
    label_en: 'Community hall / events',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Оршин суугчдын lounge',
    label_en: 'Residents’ lounge',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Ресепшн/консьерж',
    label_en: 'Reception / concierge',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Саун',
    label_en: 'Sauna',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Спа/массаж',
    label_en: 'Spa / massage',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Уурын өрөө',
    label_en: 'Steam room',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Фитнес танхим',
    label_en: 'Fitness gym',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Хоолны газар/кафетери',
    label_en: 'Food & beverage outlet',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Хурал/семинарын өрөө',
    label_en: 'Meeting / seminar room',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Хуурай хими цэвэрлэгээ',
    label_en: 'Dry cleaning',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Хүнсний дэлгүүр (канвиньенс)',
    label_en: 'Convenience store',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Хүүхдийн асаргаа/kids club',
    label_en: 'Daycare / kids club',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Хүүхдийн тоглоомын өрөө',
    label_en: 'Kids playroom (indoor)',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Эмийн сан',
    label_en: 'Pharmacy',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Эрүүл мэндийн пункт',
    label_en: 'Clinic / medical point',
    type: 'boolean',
  },
  {
    category_code: 'LIF',
    category: 'Lifestyle & Community',
    label_mн: 'Өдөр өнжүүлэх (он-сайт)',
    label_en: 'On-site kindergarten/daycare',
    type: 'boolean',
  },

  {
    category_code: 'OFF',
    category: 'Office',
    label_mn: 'HVAC бүсчлэл',
    label_en: 'HVAC zoning',
    type: 'boolean',
  },
  {
    category_code: 'OFF',
    category: 'Office',
    label_mn: 'Raised floor',
    label_en: 'Raised floor',
    type: 'boolean',
  },
  {
    category_code: 'OFF',
    category: 'Office',
    label_mn: 'UPS / давхар тэжээл',
    label_en: 'UPS / dual power feeds',
    type: 'boolean',
  },
  {
    category_code: 'OFF',
    category: 'Office',
    label_mn: 'Ажилтны дугуйн шүргэх зам/цаана',
    label_en: 'Bike facilities (showers/lockers)',
    type: 'boolean',
  },
  {
    category_code: 'OFF',
    category: 'Office',
    label_mn: 'Душ, хувцас солих өрөө',
    label_en: 'Showers & lockers',
    type: 'boolean',
  },
  {
    category_code: 'OFF',
    category: 'Office',
    label_mn: 'Сервер өрөө бэлэн',
    label_en: 'Server room ready',
    type: 'boolean',
  },
  {
    category_code: 'OFF',
    category: 'Office',
    label_mн: 'Телко redundancy (A+B)',
    label_en: 'Telecom redundancy (A+B)',
    type: 'boolean',
  },

  {
    category_code: 'HOA',
    category: 'Operations & HOA',
    label_mн: '24/7 дуудлагын төв',
    label_en: '24/7 helpdesk',
    type: 'boolean',
  },

  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'BBQ/Пикник бүс',
    label_en: 'BBQ / picnic area',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Амралтын пергола/сүүдрэвч',
    label_en: 'Pergola / gazebo',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Гадна гэрэлтүүлэг мэдрэгчтэй',
    label_en: 'Sensor outdoor lighting',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Гүйлтийн/алхалтын зам',
    label_en: 'Jogging/walking track',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Дотоод гудамж/плаза',
    label_en: 'Inner courtyard / plaza',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Нохой угаах станц',
    label_en: 'Dog wash station',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Нохойны талбай',
    label_en: 'Dog park / pet area',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Скейт парк/спорт паркур',
    label_en: 'Skate/parkour zone',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Спорт талбай (сагс/футзал)',
    label_en: 'Sports court',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Усан гоёл/фонтан',
    label_en: 'Water feature / fountain',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Хотхоны цэцэрлэгт хүрээлэн',
    label_en: 'Community park',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Хүүхдийн тоглоомын талбай',
    label_en: 'Playground',
    type: 'boolean',
  },
  {
    category_code: 'OUT',
    category: 'Outdoor & Landscape',
    label_mн: 'Цас хайлуулах халаалттай зам',
    label_en: 'Snow-melt walkway',
    type: 'boolean',
  },

  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Авто угаалгын бокс',
    label_en: 'Car wash bay',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Гадна ил зогсоол',
    label_en: 'Outdoor parking',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Газрын доорх зогсоол',
    label_en: 'Underground parking',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Газрын дээгүүр зогсоол',
    label_en: 'Above-ground parking',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Дотоод гараж дулаантай',
    label_en: 'Heated indoor garage',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Дугаар таних систем',
    label_en: 'License plate recognition',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Дугуйн зогсоол',
    label_en: 'Bicycle parking',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Дугуйн угаагч/засвар булан',
    label_en: 'Bike wash/repair corner',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Зогсоолын удирдлага (дэлгэц/сенсор)',
    label_en: 'Parking guidance system',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Зочдын зогсоол',
    label_en: 'Visitor parking',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Мотоциклын зогсоол',
    label_en: 'Motorcycle parking',
    type: 'boolean',
  },
  {
    category_code: 'PRK',
    category: 'Parking & Mobility',
    label_mн: 'Утаа соролт/агааржуулалт',
    label_en: 'Parking ventilation',
    type: 'boolean',
  },

  {
    category_code: 'RTL',
    category: 'Retail / Mall',
    label_mн: 'Food court',
    label_en: 'Food court',
    type: 'boolean',
  },
  {
    category_code: 'RTL',
    category: 'Retail / Mall',
    label_mн: 'Grease trap',
    label_en: 'Grease trap',
    type: 'boolean',
  },
  {
    category_code: 'RTL',
    category: 'Retail / Mall',
    label_mн: 'Анкер супермаркет',
    label_en: 'Anchor supermarket',
    type: 'boolean',
  },
  {
    category_code: 'RTL',
    category: 'Retail / Mall',
    label_mн: 'Ачаа буулгах док',
    label_en: 'Loading dock',
    type: 'boolean',
  },
  {
    category_code: 'RTL',
    category: 'Retail / Mall',
    label_mн: 'Гал тогооны яндан/утаа',
    label_en: 'Kitchen exhaust shaft',
    type: 'boolean',
  },
  {
    category_code: 'RTL',
    category: 'Retail / Mall',
    label_mн: 'Тусдаа тоолууржуулалт',
    label_en: 'Separate utility meters',
    type: 'boolean',
  },
  {
    category_code: 'RTL',
    category: 'Retail / Mall',
    label_mн: 'Үйлчилгээний коридор (BOH)',
    label_en: 'Back-of-house corridor',
    type: 'boolean',
  },

  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: '24/7 хамгаалалт',
    label_en: '24/7 manned security',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'CCTV хяналтын камер',
    label_en: 'CCTV surveillance',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'QR зочин бүртгэл',
    label_en: 'Visitor QR registration',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Аюулгүй байдлын дохиолол',
    label_en: 'Intrusion alarm',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Аянгын хамгаалалт',
    label_en: 'Lightning protection',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Видео домофон',
    label_en: 'Video intercom',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Галын дохиолол',
    label_en: 'Fire alarm',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Галын усан стояк/гидрант',
    label_en: 'Fire hydrant/standpipe',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Галын утаа соролт',
    label_en: 'Smoke extraction',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Даатгалд хамрагдсан',
    label_en: 'Property insured',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Дуудлагын товч (SOS)',
    label_en: 'Panic button / SOS',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Нэвтрэх хяналтын карт/чип',
    label_en: 'Access control (card/RFID)',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Нүүлгэн шилжүүлэх гарын авлага',
    label_en: 'Evacuation plan posted',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Орц бүрийн код/карт',
    label_en: 'Entrance PIN/card per door',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Орчны гэрэлтүүлгийн бодлого',
    label_en: 'Perimeter lighting policy',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Оршин суугчийн апп нэвтрэх',
    label_en: 'Resident app access control',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Усан цацагч систем',
    label_en: 'Fire sprinkler',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Утаа мэдрэгч',
    label_en: 'Smoke detector',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Хаалганы ухаалаг түгжээ',
    label_en: 'Smart lock',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Хамгаалалтын патруль',
    label_en: 'Security patrols',
    type: 'boolean',
  },
  {
    category_code: 'SEC',
    category: 'Security & Safety',
    label_mн: 'Яаралтай гэрэлтүүлэг',
    label_en: 'Emergency lighting',
    type: 'boolean',
  },

  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Air quality monitor (индекс)',
    label_en: 'Air quality monitoring',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'BMS ухаалаг систем',
    label_en: 'Building management system (BMS)',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'CO₂ мэдрэгчтэй агаарын хяналт',
    label_en: 'CO₂ monitoring',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Low-VOC материал',
    label_en: 'Low-VOC materials',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Бороо ус хуримтлуулах',
    label_en: 'Rainwater harvesting',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Дахин боловсруулах цэг',
    label_en: 'Recycling point',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Дулааны насос/геотерм',
    label_en: 'Heat pump / geothermal',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Нарны гэрэлтүүлэг таймер/фото мэдрэгч',
    label_en: 'Photocell/timer lighting',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Нарны дулааны коллектор',
    label_en: 'Solar thermal',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Нарны фотоволтайк',
    label_en: 'Solar PV',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Ногоон дээвэр',
    label_en: 'Green roof',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Саарал ус дахин ашиглалт',
    label_en: 'Greywater reuse',
    type: 'boolean',
  },
  {
    category_code: 'SUS',
    category: 'Sustainability & Smart',
    label_mн: 'Ухаалаг гэрэлтүүлэг мэдрэгчтэй',
    label_en: 'Motion-sensor lighting',
    type: 'boolean',
  },

  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Smart home пакет',
    label_en: 'Smart home package',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Агааржуулалтын соролт (гал тогоо)',
    label_en: 'Kitchen hood ducted',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Ариун цэврийн өрөө шалны халаалт',
    label_en: 'Bathroom underfloor heating',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Гал тогооны иж бүрдэл',
    label_en: 'Kitchen set',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Дуу чимээ тусгаарлагч цонх',
    label_en: 'Acoustic glazing',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Зуух / шарах шүүгээ',
    label_en: 'Oven',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Тавилга багтсан эсэх',
    label_en: 'Furniture package',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Угаалгын машин',
    label_en: 'Washer',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Унтлагын өрөөний шкаф',
    label_en: 'Built-in wardrobes',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Усан шүүлтүүр/кран',
    label_en: 'Drinking water filter/tap',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Ухаалаг термостат',
    label_en: 'Smart thermostat',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Хатаагч',
    label_en: 'Dryer',
    type: 'boolean',
  },
  {
    category_code: 'UNI',
    category: 'Unit Interior',
    label_mн: 'Хөшигний зам/карниз',
    label_en: 'Curtain tracks',
    type: 'boolean',
  },
];
